### PR TITLE
Update ttl with maxAge on cache access

### PR DESCRIPTION
**Pull request by Redsandro**
:warning: __Note:__ This PR is committed on top of #67 so this can be merged in stead of #67.

> ### #67 Added onExpire cancellation
> * Added possibility to cancel/reset `expireAfter` by returning `false` from optional `onExpire` callback.
> * Added test
> * Added missing dev dependency `babel-plugin-syntax-flow` to `package.json`

* Added ttl (expireAfter) to cache to it can be cancelled/updated
* Added `updateExpire` option to indicate expireAfter needs to reset after cache access
* Added test
* Updated tests

This fixes part 1 of #66 

---

Example:

```
moize({
    maxAge: 60000,
    updateExpire: true
})(fn)
```

On every cache hit, the value's age is reset to zero.

### CODE REVIEW

**Comment by planttheidea** [comment]
So I agree with the goal of this, but the implementation has way more changes that are necessary to implement this goal. If the sole purpose is to reset the expiration timeout, there is a way simpler way to accomplish this. these changes would also impact runtime speed for non-TTL implementations.

**Comment by Redsandro** [comment]
@planttheidea I'd love to contribute a solution that is acceptable for everyone, but void of thorough understanding of the `moize` internals, I failed to come up with a _'way simpler way'_ of making sure the expiration on an accessed cache item resets.

I implore you draft a simpler way of doing this. I've effectively made 30 line edits on code alone, lest tests/docs. I challenge you to do it in 15.

---

With this rejected, would you please review #67 in stead. It serves a different purpose and is not intrusive. There's also a missing dev dependency for tests.

**Comment by planttheidea** [comment]
It's less about lines of code as it is about adding bulk to infrastructure that impacts non-related scenarios ... adding properties to the listItem object, for example, satisfies an edge case while negatively impacting the primary use-case from a performance perspective. Apologies for the terseness of my response, I was on my phone. I've drafted a method to accomplish this requirement, and confirmed it does not impact benchmarks of standard use-cases, so once I add tests I'll merge that in.

**Comment by planttheidea** [comment]
Closed in favor of #70 . #67 will remain open, as this does not satisfy the same requirements.

**Comment by Redsandro** [comment]
You are correct. Thank you for the commit.

**Pull request closed without merging**
