### PR TITLE
Create ES2015 module transpile target

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to create a separate transpile target which preserves ES2015 modules. This is useful for Rollup and Webpack 2+ tree shaking:

- https://github.com/rollup/rollup/wiki/pkg.module
- https://webpack.js.org/guides/tree-shaking/

In my testing, taking advantage of the `module` field in [my project](https://github.com/aduth/rememo) yields a 25% size reduction in the minified build (13.7kb -> 10.4kb).

The Babel environment configuration is backwards from what I would have preferred, but apparently it is not easy to override the preset options for `modules`, at least until Babel 7.x : https://github.com/babel/babel-preset-env/issues/296

### CODE REVIEW

**Comment by planttheidea** [comment]
Thanks for the submission! Let me pull this down and check it out, but I think this would be a great addition.

**Comment by planttheidea** [comment]
So I pulled this down, and noticed a couple of issues
* The tests break (as modules are no longer being transpiled)
* The `es` output still has `module.exports = exports['default'];` which is produced by the `add-module-exports` plugin

You are correct in that there is not an easy way to override the preset options for modules ... so I went the hard way haha. I was able to get it working by:
* Removing `NODE_ENV=production` from the `transpile` scripts
  * It wasn't doing anything before anyway, and you already added `BABEL_ENV=es`, so I worked with that
* Changing `.babelrc` to be the following:

```
{
  "env": {
    "development": {
      "plugins": ["add-module-exports"],
      "presets": [
        [ "env", {
          "loose": true
        }],
        "stage-2"
      ]
    },
    "es": {
        [ "env", {
          "loose": true,
          "modules": false
        }],
        "stage-2"
      ]
    },
    "production": {
      "plugins": ["add-module-exports"],
        [ "env", {
          "loose": true
        }],
        "stage-2"
      ]
    },
    "test": {
      "presets": [
        [ "env", {
          "loose": true
        }],
        "stage-2"
      ]
    }
  },
  "plugins": ["syntax-flow", "transform-flow-strip-types"]
}
```

Not exactly DRY, but ... it ensures that `"modules": false` is only applied when `BABEL_ENV` is `es`, and also ensures that `add-module-exports` plugin is only applied for `development` and `production`, which prevents it from being applied in `es`.

I didn't want to just merge my changes onto your PR, so I figured I'd just lay out the changes I did to make it work and see if you wanted to tweak from there. Let me know what you think.

**Comment by aduth** [comment]
Thanks for the pointers @planttheidea . I really don't mind if you make the changes directly to my branch - you should have permission to do so. I was going to apply your recommendation, but one issue: You mention you removed `NODE_ENV=production` from transpile scripts, but wouldn't you still need it for `transpile:lib` ? Or otherwise do you need the `production` key in `env` at all (since it matches `development` default anyways?).

**Comment by planttheidea** [comment]
I removed it from the transpile lib script because it's unused there, but it's definitely used in the Webpack build for the minified dist file that also gets published (in case they want a built version to noParse or something). 

If you are willing to wait about a day, I should be able to focus on this more actively ... I've been on vacation in Italy this week, but we fly back tomorrow, and once I'm home I can crank on the non-travel machine.

**Comment by aduth** [comment]
No worries at all. Enjoy your vacation!

**Pull request merged**
